Feature/update documentation
studiometa/create-wordpress-project pull request #24
Opened 2020-10-20 13:21 UTC by perruche

**Add documentation about the post installation process**
- in the shell after the project is created
- in the readme of this project

**Add the `WP_DEFAULT_THEME` constant to automatically activate our theme**

**Add the execution of `bin/generate-wp-config.sh`script to the project creation process**

2020-10-20 13:58 UTC, titouanmathis requested changes
Some minor typo to fix, all good for me otherwise!

2020-10-20 13:58 UTC, titouanmathis commented on readme.md
> +Follow the prompt steps to complete the project creation
There is a `.` missing at the end of the sentence

2020-10-20 13:58 UTC, titouanmathis commented on saofile.js
> +    console.log(chalk`${tab}Install development dependancies:`);
There is a typo in `dependencies`.

2020-10-22 11:35 UTC, titouanmathis approved these changes
👍

2020-10-22 11:51 UTC, lusimeon approved these changes

2020-10-22 11:53 UTC, titouanmathis approved these changes

2020-10-22 11:58 UTC, merged